

version: '3'
services:
  jupyterlab:
    build: .
    volumes:
      - '/data/jupyter:/workspace'
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    container_name: jupyterlab
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/ShangHai 
    command: /bin/bash -c "jupyter lab --NotebookApp.password=${ACCESS_TOKEN}   --ip='*' --port=8888 --no-browser --allow-root"
  