version: '3'
services:
  jupyterlab:
    build: .
    volumes:
      - '/home/data:/workspace'
    
    container_name: jupyterlab
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/ShangHai